/**
 * lib/routeAdvisor.js
 * ─────────────────────────────────────────────────────────────────
 * Modul untuk auto-routing dan dokumentasi in-terminal.
 * - Untuk framework dengan routing kompleks (Laravel): coba
 *   injeksi route otomatis ke web.php dengan konfirmasi user.
 * - Untuk framework lain: cetak panduan langkah demi langkah.
 * ─────────────────────────────────────────────────────────────────
 */

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const inquirer = require('inquirer');

// ─── Konstanta ─────────────────────────────────────────────────

/**
 * ┌─ KUSTOMISASI ────────────────────────────────────────────────┐
 * │ Sesuaikan ROUTE_PATH jika struktur folder Laravel berbeda.   │
 * │ BLADE_VIEW_NAME: nama view Blade yang akan dipanggil di route │
 * └──────────────────────────────────────────────────────────────┘
 */
const LARAVEL_ROUTE_FILE = 'routes/web.php';
const BLADE_VIEW_NAME = 'FutureCloudMonitoring'; // nama file .blade.php tanpa ekstensi

// ─── Fungsi Utama ──────────────────────────────────────────────

/**
 * Entry point utama — menjalankan panduan/auto-routing sesuai framework.
 * 
 * @param {Object} frameworkMeta - Metadata framework dari frameworkSelector
 * @param {string} deployedFilePath - Path absolut file widget yang sudah dibuat
 */
async function runRouteAdvisor(frameworkMeta, deployedFilePath, licenseKey) {
  console.log(chalk.cyan('\n[INFO]  Langkah 4: Panduan Integrasi\n'));

  switch (frameworkMeta.name) {
    case 'Laravel':
      await handleLaravel(deployedFilePath, licenseKey);
      break;
    case 'React':
      handleReact(deployedFilePath);
      break;
    case 'Vue':
      handleVue(deployedFilePath);
      break;
    case 'HTML Biasa':
      handleHtml(deployedFilePath);
      break;
    default:
      printGenericGuide(deployedFilePath);
  }
}

// ─── Handler per Framework ─────────────────────────────────────

/**
 * Handler Laravel: Coba injeksi route ke web.php dengan konfirmasi.
 */
async function handleLaravel(deployedFilePath, licenseKey) {
  const routeFilePath = path.join(process.cwd(), LARAVEL_ROUTE_FILE);
  const routeExists = fs.existsSync(routeFilePath);

  // ── Coba auto-route ──────────────────────────────────────────
  if (routeExists) {
    console.log(chalk.gray(`   [FILE] Ditemukan: ${LARAVEL_ROUTE_FILE}`));

    const { doAutoRoute } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'doAutoRoute',
        message: `Tambahkan route /monitoring-widget secara otomatis ke ${LARAVEL_ROUTE_FILE}?`,
        default: true,
      },
    ]);

    if (doAutoRoute) {
      const routeSnippet = buildLaravelRouteSnippet(licenseKey);
      let routeContent = fs.readFileSync(routeFilePath, 'utf8');

      // Cek apakah route sudah ada agar tidak duplikasi
      if (routeContent.includes('futurecloud-monitoring-widget') || routeContent.includes('futurecloud-admin-monitoring')) {
        console.log(chalk.yellow(`   [WARNING]  Route sudah ada di ${LARAVEL_ROUTE_FILE}, dilewati.`));
      } else {
        routeContent += routeSnippet;
        fs.writeFileSync(routeFilePath, routeContent, 'utf8');
        console.log(chalk.green(`   [SUCCESS]  Route berhasil ditambahkan ke ${LARAVEL_ROUTE_FILE}`));
      }
    }
  }

  // ── Selalu tampilkan panduan manual sebagai referensi ─────────
  printLaravelGuide(deployedFilePath, routeExists);
}

/**
 * Handler React.
 */
function handleReact(deployedFilePath) {
  printReactGuide(deployedFilePath);
}

/**
 * Handler Vue.
 */
function handleVue(deployedFilePath) {
  printVueGuide(deployedFilePath);
}

/**
 * Handler HTML Biasa.
 */
function handleHtml(deployedFilePath) {
  printHtmlGuide(deployedFilePath);
}

// ─── Builder Snippet Route ─────────────────────────────────────

/**
 * Membangun snippet route Laravel yang akan diinjeksi ke web.php.
 */
function buildLaravelRouteSnippet(licenseKey) {
  return `

// ── FutureCloud Monitoring Routes (auto-generated by CLI) ──
Route::get('/monitoring-widget', function () {
    return view('${BLADE_VIEW_NAME}');
})->name('futurecloud-monitoring-widget');


`;
}

// ─── Panduan Terminal per Framework ───────────────────────────

function printLaravelGuide(deployedFilePath, routeFileFound) {
  const relativePath = path.relative(process.cwd(), deployedFilePath).replace(/\\/g, '/');

  console.log('\n' + chalk.cyan('━━━ Panduan Integrasi Laravel ━━━') + '\n');

  if (!routeFileFound) {
    console.log(
      chalk.yellow('  [WARNING]  File routes/web.php tidak ditemukan.') +
      chalk.gray(' Pastikan Anda menjalankan CLI dari root proyek Laravel.\n')
    );
  }

  console.log(chalk.white('  1. File Blade widget sudah tersedia di:'));
  console.log(chalk.cyan(`     ${relativePath}\n`));

  console.log(chalk.white('  2. Tambahkan route berikut di routes/web.php:'));
  console.log(chalk.gray(`
     Route::get('/monitoring-widget', function () {
         return view('${BLADE_VIEW_NAME}');
     })->name('futurecloud-monitoring-widget');
  `));

  console.log(chalk.white('  3. Sertakan komponen di layout utama (resources/views/layouts/app.blade.php):'));
  console.log(chalk.gray(`
     @include('${BLADE_VIEW_NAME}')
     {{-- atau --}}
     <x-futurecloud-monitoring />
  `));

  console.log(chalk.white('  4. Pastikan Laravel Mix/Vite Anda tidak mengecualikan folder resources/views.'));

  }

function printReactGuide(deployedFilePath) {
  const relativePath = path.relative(process.cwd(), deployedFilePath).replace(/\\/g, '/');
  const componentName = path.basename(deployedFilePath, '.jsx');

  console.log('\n' + chalk.cyan('━━━ Panduan Integrasi React ━━━') + '\n');

  console.log(chalk.white('  1. File komponen sudah tersedia di:'));
  console.log(chalk.cyan(`     ${relativePath}\n`));

  console.log(chalk.white('  2. Import dan gunakan di App.jsx atau layout utama Anda:'));
  console.log(chalk.gray(`
     import ${componentName} from './${relativePath}';

     function App() {
       return (
         <>
           {/* ... konten app Anda */}
           <${componentName} />  {/* ← Tambahkan di sini */}
         </>
       );
     }
  `));

  console.log(chalk.white('  3. (Opsional) Jika menggunakan Next.js, tambahkan ke pages/_app.jsx:'));
  console.log(chalk.gray(`
     import ${componentName} from '../${relativePath}';

     export default function MyApp({ Component, pageProps }) {
       return (
         <>
           <Component {...pageProps} />
           <${componentName} />
         </>
       );
     }
  `));

  }

function printVueGuide(deployedFilePath) {
  const relativePath = path.relative(process.cwd(), deployedFilePath).replace(/\\/g, '/');
  const componentName = path.basename(deployedFilePath, '.vue');

  console.log('\n' + chalk.cyan('━━━ Panduan Integrasi Vue ━━━') + '\n');

  console.log(chalk.white('  1. File SFC sudah tersedia di:'));
  console.log(chalk.cyan(`     ${relativePath}\n`));

  console.log(chalk.white('  2. Import dan daftarkan di App.vue:'));
  console.log(chalk.gray(`
     <template>
       <div>
         <!-- ... konten app Anda -->
         <${componentName} />  <!-- ← Tambahkan di sini -->
       </div>
     </template>

     <script>
     import ${componentName} from './${relativePath}';

     export default {
       components: { ${componentName} }
     };
     </script>
  `));

  console.log(chalk.white('  3. Atau daftarkan secara global di main.js:'));
  console.log(chalk.gray(`
     import { createApp } from 'vue';
     import ${componentName} from './${relativePath}';

     const app = createApp(App);
     app.component('${componentName}', ${componentName});
     app.mount('#app');
  `));

  }

function printHtmlGuide(deployedFilePath) {
  const relativePath = path.relative(process.cwd(), deployedFilePath).replace(/\\/g, '/');

  console.log('\n' + chalk.cyan('━━━ Panduan Integrasi HTML Biasa ━━━') + '\n');

  console.log(chalk.white('  1. File widget sudah tersedia di:'));
  console.log(chalk.cyan(`     ${relativePath}\n`));

  console.log(chalk.white('  2. Tambahkan script tag berikut sebelum </body> di file HTML Anda:'));
  console.log(chalk.gray(`
     <script src="${relativePath}"></script>
  `));

  console.log(chalk.white('  3. Contoh lengkap:'));
  console.log(chalk.gray(`
     <!DOCTYPE html>
     <html>
       <head>
         <title>Website Anda</title>
       </head>
       <body>
         <!-- ... konten website Anda -->

         <!-- FutureCloud Monitoring Plugin -->
         <script src="${relativePath}"></script>
       </body>
     </html>
  `));

  console.log(chalk.white('  4. Widget akan muncul otomatis di sudut kanan bawah halaman.'));

  }

function printGenericGuide(deployedFilePath) {
  const relativePath = path.relative(process.cwd(), deployedFilePath).replace(/\\/g, '/');
  console.log(chalk.white(`\n  [STEP] File widget tersedia di: ${chalk.cyan(relativePath)}`));
  console.log(chalk.gray('  Sertakan file ini ke dalam proyek Anda sesuai kebutuhan framework.\n'));
}

module.exports = { runRouteAdvisor };
