/**
 * FutureCloud Monitoring Tracker
 * 
 * This file is automatically generated by the FutureCloud CLI.
 * It tracks visitor data and sends it to the FutureCloud backend.
 */

(function() {
    const LICENSE_KEY = '__LICENSE_KEY__';
    const API_URL = '__API_URL__';

    // Generate a simple session ID if not exists
    let sessionId = localStorage.getItem('fc_session_id');
    if (!sessionId) {
        sessionId = 'fc_' + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
        localStorage.setItem('fc_session_id', sessionId);
    }

    // Gather minimal data
    const data = {
        session_id: sessionId,
        page_url: window.location.href,
        device: /Mobi|Android/i.test(navigator.userAgent) ? 'Mobile' : 'Desktop',
        browser: getBrowserName(),
        os: getOSName()
    };

    // Send tracking data to the backend API
    fetch(`${API_URL}/visitor/track`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-FutureCloud-License': LICENSE_KEY,
            'Accept': 'application/json'
        },
        body: JSON.stringify(data)
    })
    .then(response => {
        if (!response.ok) {
            console.warn('FutureCloud Tracker: Failed to track visitor (maybe invalid license).');
        }
    })
    .catch(err => {
        // Silently fail if network error
    });

    // Helper functions
    function getBrowserName() {
        const agent = navigator.userAgent;
        if (agent.includes('Firefox')) return 'Firefox';
        if (agent.includes('Chrome')) return 'Chrome';
        if (agent.includes('Safari')) return 'Safari';
        return 'Unknown';
    }

    function getOSName() {
        const agent = navigator.userAgent;
        if (agent.includes('Win')) return 'Windows';
        if (agent.includes('Mac')) return 'MacOS';
        if (agent.includes('Linux')) return 'Linux';
        if (agent.includes('Android')) return 'Android';
        if (agent.includes('like Mac')) return 'iOS';
        return 'Unknown';
    }
})();
