/**
 * FutureCloud Monitoring & Interactive Chat Plugin
 * 
 * This file is automatically generated and injected by the FutureCloud CLI.
 * It tracks visitor data and provides an elegant AI Chatbot + Live Support interface.
 */

(function() {
    const LICENSE_KEY = '__LICENSE_KEY__';
    const API_URL = '__API_URL__';

    // ==========================================
    // 1. TRAFFIC MONITORING LOGIC (Background)
    // ==========================================
    function trackVisitor() {
        let sessionId = localStorage.getItem('fc_session_id');
        if (!sessionId) {
            sessionId = 'fc_' + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
            localStorage.setItem('fc_session_id', sessionId);
        }

        const data = {
            session_id: sessionId,
            page_url: window.location.href,
            device: /Mobi|Android/i.test(navigator.userAgent) ? 'Mobile' : 'Desktop',
            browser: getBrowserName(),
            os: getOSName()
        };

        // Send tracking data to the backend API
        fetch(`${API_URL}/visitor/track`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-FutureCloud-License': LICENSE_KEY,
                'Accept': 'application/json'
            },
            body: JSON.stringify(data)
        })
        .then(response => {
            if (!response.ok) {
                console.warn('FutureCloud Tracker: Active monitoring initialized (License validation pending).');
            }
        })
        .catch(err => {
            // Silently fail in case of network issues
        });
    }

    function getBrowserName() {
        const agent = navigator.userAgent;
        if (agent.includes('Firefox')) return 'Firefox';
        if (agent.includes('Chrome')) return 'Chrome';
        if (agent.includes('Safari')) return 'Safari';
        return 'Unknown';
    }

    function getOSName() {
        const agent = navigator.userAgent;
        if (agent.includes('Win')) return 'Windows';
        if (agent.includes('Mac')) return 'MacOS';
        if (agent.includes('Linux')) return 'Linux';
        if (agent.includes('Android')) return 'Android';
        if (agent.includes('like Mac')) return 'iOS';
        return 'Unknown';
    }

    // Initialize visitor traffic monitoring
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
        trackVisitor();
    } else {
        document.addEventListener('DOMContentLoaded', trackVisitor);
    }

    // ==========================================
    // 2. STUNNING UI INJECTION (Floating Widget)
    // ==========================================
    
    // Inject Custom Premium CSS Styles
    const cssStyles = `
        /* FutureCloud Widget Reset & Base */
        #fc-widget-container * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        }
        
        /* Floating Launcher Button */
        .fc-launcher {
            position: fixed;
            bottom: 24px;
            right: 24px;
            width: 60px;
            height: 60px;
            border-radius: 50%;
            background: linear-gradient(135deg, #6366f1, #06b6d4);
            box-shadow: 0 4px 20px rgba(99, 102, 241, 0.4);
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 999999;
            transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
        }
        
        .fc-launcher:hover {
            transform: scale(1.08) rotate(5deg);
            box-shadow: 0 6px 24px rgba(99, 102, 241, 0.5);
        }
        
        .fc-launcher svg {
            width: 28px;
            height: 28px;
            fill: white;
            transition: transform 0.3s ease;
        }

        .fc-launcher.active svg {
            transform: rotate(90deg);
        }
        
        /* Pulse Animation on Online Status */
        .fc-pulse-badge {
            position: absolute;
            top: 2px;
            right: 2px;
            width: 14px;
            height: 14px;
            border-radius: 50%;
            background-color: #10b981;
            border: 2px solid white;
        }
        
        .fc-pulse-ring {
            position: absolute;
            top: 0;
            right: 0;
            width: 14px;
            height: 14px;
            border-radius: 50%;
            border: 2px solid #10b981;
            animation: fc-pulse 1.8s infinite ease-out;
            opacity: 0;
        }
        
        @keyframes fc-pulse {
            0% { transform: scale(0.6); opacity: 1; }
            100% { transform: scale(2.2); opacity: 0; }
        }

        /* Glassmorphism Chat Window */
        .fc-chat-window {
            position: fixed;
            bottom: 96px;
            right: 24px;
            width: 380px;
            height: 580px;
            max-height: calc(100vh - 120px);
            border-radius: 20px;
            background: rgba(255, 255, 255, 0.85);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid rgba(255, 255, 255, 0.4);
            box-shadow: 0 12px 40px rgba(31, 38, 135, 0.12);
            z-index: 999998;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            opacity: 0;
            transform: translateY(20px) scale(0.95);
            pointer-events: none;
            transition: all 0.3s cubic-bezier(0.165, 0.84, 0.44, 1);
        }
        
        .fc-chat-window.active {
            opacity: 1;
            transform: translateY(0) scale(1);
            pointer-events: all;
        }

        @media (max-width: 480px) {
            .fc-chat-window {
                right: 12px;
                left: 12px;
                bottom: 90px;
                width: calc(100% - 24px);
                height: calc(100% - 110px);
            }
        }
        
        /* Chat Header */
        .fc-header {
            background: linear-gradient(135deg, #6366f1, #06b6d4);
            padding: 20px;
            color: white;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .fc-header-info {
            display: flex;
            align-items: center;
            gap: 12px;
        }
        
        .fc-header-avatar {
            width: 42px;
            height: 42px;
            border-radius: 50%;
            background: rgba(255, 255, 255, 0.2);
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 18px;
            border: 2px solid rgba(255, 255, 255, 0.4);
        }
        
        .fc-header-title {
            font-weight: 600;
            font-size: 16px;
            letter-spacing: 0.3px;
        }
        
        .fc-header-status {
            font-size: 12px;
            color: rgba(255, 255, 255, 0.85);
            display: flex;
            align-items: center;
            gap: 6px;
            margin-top: 2px;
        }
        
        .fc-status-dot {
            width: 8px;
            height: 8px;
            background: #10b981;
            border-radius: 50%;
            display: inline-block;
        }
        
        .fc-header-close {
            background: none;
            border: none;
            color: white;
            cursor: pointer;
            opacity: 0.8;
            transition: opacity 0.2s;
            display: flex;
            align-items: center;
        }
        
        .fc-header-close:hover {
            opacity: 1;
        }

        /* Tabs Selection */
        .fc-tabs {
            display: flex;
            background: rgba(243, 244, 246, 0.6);
            border-bottom: 1px solid rgba(229, 231, 235, 0.5);
            padding: 2px;
        }
        
        .fc-tab-btn {
            flex: 1;
            padding: 12px 8px;
            background: none;
            border: none;
            font-size: 13px;
            font-weight: 600;
            color: #6b7280;
            cursor: pointer;
            transition: all 0.2s;
            text-align: center;
            border-radius: 6px;
            margin: 2px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 6px;
        }
        
        .fc-tab-btn:hover {
            color: #374151;
            background: rgba(255, 255, 255, 0.4);
        }
        
        .fc-tab-btn.active {
            color: #4f46e5;
            background: white;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
        }

        /* Message Area */
        .fc-chat-body {
            flex: 1;
            overflow-y: auto;
            padding: 16px;
            display: flex;
            flex-direction: column;
            gap: 12px;
            background: rgba(255, 255, 255, 0.5);
        }
        
        /* Message Bubbles */
        .fc-msg {
            max-width: 80%;
            padding: 12px 16px;
            border-radius: 16px;
            font-size: 14px;
            line-height: 1.45;
            animation: fc-msg-appear 0.25s ease-out forwards;
            opacity: 0;
            transform: translateY(10px);
        }
        
        @keyframes fc-msg-appear {
            to { opacity: 1; transform: translateY(0); }
        }
        
        .fc-msg.bot {
            align-self: flex-start;
            background: #f3f4f6;
            color: #1f2937;
            border-bottom-left-radius: 4px;
        }
        
        .fc-msg.user {
            align-self: flex-end;
            background: linear-gradient(135deg, #6366f1, #4f46e5);
            color: white;
            border-bottom-right-radius: 4px;
        }
        
        .fc-msg.system {
            align-self: center;
            max-width: 90%;
            background: rgba(224, 231, 255, 0.7);
            color: #4338ca;
            font-size: 11px;
            font-weight: 600;
            padding: 6px 12px;
            border-radius: 20px;
            text-align: center;
        }
        
        /* Typing Indicator */
        .fc-typing-indicator {
            align-self: flex-start;
            background: #f3f4f6;
            padding: 12px 18px;
            border-radius: 16px;
            border-bottom-left-radius: 4px;
            display: flex;
            gap: 4px;
            align-items: center;
            min-height: 38px;
        }
        
        .fc-typing-dot {
            width: 7px;
            height: 7px;
            background: #9ca3af;
            border-radius: 50%;
            animation: fc-bounce 1.4s infinite ease-in-out both;
        }
        
        .fc-typing-dot:nth-child(1) { animation-delay: -0.32s; }
        .fc-typing-dot:nth-child(2) { animation-delay: -0.16s; }
        
        @keyframes fc-bounce {
            0%, 80%, 100% { transform: scale(0); }
            40% { transform: scale(1); }
        }

        /* Chat Footer & Input Form */
        .fc-chat-footer {
            padding: 12px 16px;
            border-top: 1px solid rgba(229, 231, 235, 0.5);
            background: white;
            display: flex;
            flex-direction: column;
            gap: 8px;
        }
        
        .fc-input-form {
            display: flex;
            gap: 8px;
            position: relative;
        }
        
        .fc-chat-input {
            flex: 1;
            padding: 10px 14px;
            border: 1px solid #e5e7eb;
            border-radius: 24px;
            font-size: 14px;
            outline: none;
            transition: border-color 0.2s, box-shadow 0.2s;
            resize: none;
            max-height: 80px;
            overflow-y: auto;
        }
        
        .fc-chat-input:focus {
            border-color: #6366f1;
            box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.15);
        }
        
        .fc-send-btn {
            width: 38px;
            height: 38px;
            border-radius: 50%;
            background: linear-gradient(135deg, #6366f1, #4f46e5);
            border: none;
            color: white;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: transform 0.2s, background 0.2s;
            align-self: flex-end;
            flex-shrink: 0;
        }
        
        .fc-send-btn:hover {
            transform: scale(1.05);
            box-shadow: 0 2px 8px rgba(99, 102, 241, 0.3);
        }
        
        .fc-send-btn svg {
            width: 18px;
            height: 18px;
            fill: white;
        }
        
        .fc-brand-link {
            font-size: 11px;
            color: #9ca3af;
            text-align: center;
            text-decoration: none;
            display: block;
            margin-top: 2px;
            font-weight: 500;
            transition: color 0.2s;
        }
        
        .fc-brand-link:hover {
            color: #6b7280;
        }

        /* ==========================================
         * 3. MONITORING DASHBOARD PREMIUM STYLING
         * ========================================== */
        .fc-dashboard-container {
            width: 100%;
            max-width: 1200px;
            margin: 0 auto;
            padding: 30px 15px;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #1e293b;
        }
        
        /* Top Banner Header */
        .fc-db-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px 24px;
            background: linear-gradient(135deg, #1e1b4b, #312e81);
            color: white;
            border-radius: 16px;
            margin-bottom: 24px;
            box-shadow: 0 10px 25px -5px rgba(49, 46, 129, 0.2);
        }
        
        .fc-db-logo {
            font-size: 20px;
            font-weight: 800;
            letter-spacing: 0.5px;
            background: linear-gradient(to right, #818cf8, #38bdf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        
        .fc-db-badge {
            display: flex;
            align-items: center;
            gap: 8px;
            background: rgba(16, 185, 129, 0.15);
            color: #34d399;
            border: 1px solid rgba(16, 185, 129, 0.3);
            padding: 6px 14px;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 600;
        }
        
        .fc-db-status-pulse {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            background-color: #34d399;
            box-shadow: 0 0 0 0 rgba(52, 211, 153, 0.7);
            animation: fc-db-pulse-anim 1.6s infinite;
        }
        
        @keyframes fc-db-pulse-anim {
            0% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(52, 211, 153, 0.7); }
            70% { transform: scale(1); box-shadow: 0 0 0 6px rgba(52, 211, 153, 0); }
            100% { transform: scale(0.95); box-shadow: 0 0 0 0 rgba(52, 211, 153, 0); }
        }
        
        /* Stats Grid Cards */
        .fc-db-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 24px;
            margin-bottom: 28px;
        }
        
        .fc-db-card {
            background: white;
            border-radius: 16px;
            padding: 24px;
            border: 1px solid rgba(226, 232, 240, 0.8);
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            min-height: 120px;
            transition: transform 0.2s, box-shadow 0.2s;
        }
        
        .fc-db-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.08);
        }
        
        .fc-db-card h4 {
            font-size: 13px;
            font-weight: 600;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 8px;
        }
        
        .fc-db-card-val {
            font-size: 36px;
            font-weight: 800;
            color: #1e1b4b;
        }
        
        /* Log Table Section */
        .fc-db-table-card {
            background: white;
            border-radius: 16px;
            padding: 24px;
            border: 1px solid rgba(226, 232, 240, 0.8);
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        }
        
        .fc-db-table-card h3 {
            font-size: 18px;
            font-weight: 700;
            color: #0f172a;
            margin-bottom: 18px;
        }
        
        .fc-db-table-wrapper {
            overflow-x: auto;
            width: 100%;
        }
        
        .fc-db-table {
            width: 100%;
            border-collapse: collapse;
            text-align: left;
            font-size: 14px;
        }
        
        .fc-db-table th {
            padding: 14px 16px;
            background: #f8fafc;
            color: #475569;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 12px;
            letter-spacing: 0.5px;
            border-bottom: 2px solid #edf2f7;
        }
        
        .fc-db-table td {
            padding: 16px;
            border-bottom: 1px solid #edf2f7;
            color: #334155;
            vertical-align: middle;
        }
        
        .fc-db-table tr:hover td {
            background: #f8fafc;
        }
        
        /* Log Badges & Paths formatting */
        .fc-db-session {
            font-weight: 700;
            font-family: monospace;
            color: #4f46e5;
            background: #f5f3ff;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 12px;
        }
        
        .fc-db-date {
            font-size: 12px;
            color: #64748b;
            margin-top: 4px;
        }
        
        .fc-db-path-list {
            list-style: none;
            display: flex;
            flex-direction: column;
            gap: 4px;
        }
        
        .fc-db-path-badge {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            background: #eff6ff;
            color: #2563eb;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
            border: 1px solid #dbeafe;
        }
        
        .fc-db-path-time {
            font-size: 10px;
            color: #94a3b8;
        }
        
        .fc-db-location {
            font-size: 13px;
            font-weight: 500;
        }
        
        .fc-db-ip {
            font-size: 11px;
            color: #94a3b8;
            margin-top: 3px;
            font-family: monospace;
        }
        
        .fc-db-info-footer {
            margin-top: 24px;
            padding: 16px;
            background: #f0fdf4;
            color: #166534;
            border-radius: 12px;
            font-size: 13px;
            font-weight: 500;
            border: 1px solid #bbf7d0;
            display: flex;
            align-items: center;
            gap: 8px;
        }
    `;

    // Inject SVG Definitions
    const iconClose = `<svg viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>`;
    const iconSend = `<svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>`;
    const iconChat = `<svg viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/></svg>`;
    const iconBot = `<svg style="width:14px;height:14px;" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A2,2 0 0,1 14,4C14,4.74 13.6,5.39 13,5.73V7H14A3,3 0 0,1 17,10V11H18A2,2 0 0,1 20,13V15A2,2 0 0,1 18,17H17V18A3,3 0 0,1 14,21H10A3,3 0 0,1 7,18V17H6A2,2 0 0,1 4,15V13A2,2 0 0,1 6,11H7V10A3,3 0 0,1 10,7H11V5.73C10.4,5.39 10,4.74 10,4A2,2 0 0,1 12,2M7.5,13A1.5,1.5 0 0,0 6,14.5A1.5,1.5 0 0,0 7.5,16A1.5,1.5 0 0,0 9,14.5A1.5,1.5 0 0,0 7.5,13M16.5,13A1.5,1.5 0 0,0 15,14.5A1.5,1.5 0 0,0 16.5,16A1.5,1.5 0 0,0 18,14.5A1.5,1.5 0 0,0 16.5,13M12,9A2,2 0 0,0 10,11V12H14V11A2,2 0 0,0 12,9Z" /></svg>`;
    const iconAgent = `<svg style="width:14px;height:14px;" viewBox="0 0 24 24"><path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A2,2 0 0,1 14,6A2,2 0 0,1 12,8A2,2 0 0,1 10,6A2,2 0 0,1 12,4M12,18c-2.67,0-8,1.34-8,4v-2c0-2.66,5.33-4,8-4c2.67,0,8,1.34,8,4v2c0-2.66-5.33-4-8-4z" /></svg>`;

    // Interactive State Manager
    const state = {
        isOpen: false,
        activeTab: 'ai', // 'ai' or 'live'
        aiMessages: [
            { sender: 'bot', text: 'Halo! Saya adalah Asisten AI FutureCloud. Bagaimana saya bisa membantu Anda hari ini?' }
        ],
        liveMessages: [
            { sender: 'system', text: 'Menghubungkan ke Tim Support FutureCloud...' }
        ],
        liveStatus: 'connecting', // 'connecting', 'connected'
        sarahJoined: false
    };

    // Simulated dashboard fallback data (Visitor Journey Log)
    const mockVisitorData = {
        total_visitors: 1420,
        today_visitors: 54,
        visitor_logs: [
            {
                session_id: "fc_9d3k9s2a1h4",
                date: "09 Jul 2026",
                page_journey: [
                    { path: "/home", time: "16:20:10" },
                    { path: "/products", time: "16:21:45" },
                    { path: "/dashboard", time: "16:23:05" }
                ],
                device: "Desktop",
                browser: "Chrome",
                city: "Jakarta",
                country: "Indonesia",
                ip_address: "182.253.140.85"
            },
            {
                session_id: "fc_2a8s9k1h5c4",
                date: "09 Jul 2026",
                page_journey: [
                    { path: "/home", time: "15:45:12" },
                    { path: "/about", time: "15:48:30" }
                ],
                device: "Mobile",
                browser: "Safari",
                city: "Surabaya",
                country: "Indonesia",
                ip_address: "110.138.25.10"
            },
            {
                session_id: "fc_7h3l8w2x1v9",
                date: "09 Jul 2026",
                page_journey: [
                    { path: "/contact", time: "14:12:00" }
                ],
                device: "Desktop",
                browser: "Firefox",
                city: "Bandung",
                country: "Indonesia",
                ip_address: "36.85.120.4"
            },
            {
                session_id: "fc_5v8n3m1q6p2",
                date: "08 Jul 2026",
                page_journey: [
                    { path: "/home", time: "23:55:18" },
                    { path: "/checkout", time: "23:59:40" }
                ],
                device: "Mobile",
                browser: "Chrome",
                city: "Medan",
                country: "Indonesia",
                ip_address: "103.22.180.12"
            }
        ]
    };

    // ==========================================
    // 3. UI INITIALIZER & RENDERING FLOW
    // ==========================================
    function setupUI() {
        // Prevent duplicate setups
        if (document.getElementById('fc-widget-container')) return;

        // 1. Inject Styles
        const styleSheet = document.createElement('style');
        styleSheet.textContent = cssStyles;
        document.head.appendChild(styleSheet);

        // 2. Render Analytics Dashboard if matching paths
        renderDashboard();

        // 3. Create Widget Wrapper
        const wrapper = document.createElement('div');
        wrapper.id = 'fc-widget-container';
        
        // Render Floating Launcher
        const launcher = document.createElement('div');
        launcher.className = 'fc-launcher';
        launcher.innerHTML = `
            ${iconChat}
            <div class="fc-pulse-badge"></div>
            <div class="fc-pulse-ring"></div>
        `;
        wrapper.appendChild(launcher);

        // Render Chat Window
        const chatWindow = document.createElement('div');
        chatWindow.className = 'fc-chat-window';
        chatWindow.innerHTML = `
            <!-- Header -->
            <div class="fc-header">
                <div class="fc-header-info">
                    <div class="fc-header-avatar">FC</div>
                    <div>
                        <div class="fc-header-title">FutureCloud Workspace</div>
                        <div class="fc-header-status">
                            <span class="fc-status-dot"></span>
                            <span>Online</span>
                        </div>
                    </div>
                </div>
                <button class="fc-header-close" title="Minimize">${iconClose}</button>
            </div>
            
            <!-- Tabs selection -->
            <div class="fc-tabs">
                <button class="fc-tab-btn active" data-tab="ai">${iconBot} AI Chatbot</button>
                <button class="fc-tab-btn" data-tab="live">${iconAgent} Live Support</button>
            </div>
            
            <!-- Chat Log -->
            <div class="fc-chat-body"></div>
            
            <!-- Input Bar -->
            <div class="fc-chat-footer">
                <form class="fc-input-form">
                    <input type="text" class="fc-chat-input" placeholder="Tulis pesan Anda..." autocomplete="off" />
                    <button type="submit" class="fc-submit-btn fc-send-btn">${iconSend}</button>
                </form>
                <a href="https://futurecloud.id" target="_blank" class="fc-brand-link">Powered by FutureCloud</a>
            </div>
        `;
        wrapper.appendChild(chatWindow);
        document.body.appendChild(wrapper);

        // Cache Element Selectors
        const elements = {
            launcher,
            chatWindow,
            closeBtn: chatWindow.querySelector('.fc-header-close'),
            tabBtns: chatWindow.querySelectorAll('.fc-tab-btn'),
            chatBody: chatWindow.querySelector('.fc-chat-body'),
            inputForm: chatWindow.querySelector('.fc-input-form'),
            chatInput: chatWindow.querySelector('.fc-chat-input')
        };

        // Render Initial Messages
        renderMessages(elements.chatBody);

        // Event: Toggle Chat Open/Close
        elements.launcher.addEventListener('click', () => {
            state.isOpen = !state.isOpen;
            if (state.isOpen) {
                elements.chatWindow.classList.add('active');
                elements.launcher.classList.add('active');
                elements.chatInput.focus();
                scrollToBottom(elements.chatBody);
                
                // If switching to live chat for first time, trigger simulated connect
                if (state.activeTab === 'live' && !state.sarahJoined) {
                    triggerLiveConnection(elements.chatBody);
                }
            } else {
                elements.chatWindow.classList.remove('active');
                elements.launcher.classList.remove('active');
            }
        });

        elements.closeBtn.addEventListener('click', () => {
            state.isOpen = false;
            elements.chatWindow.classList.remove('active');
            elements.launcher.classList.remove('active');
        });

        // Event: Tabs Switching
        elements.tabBtns.forEach(btn => {
            btn.addEventListener('click', (e) => {
                const targetTab = btn.getAttribute('data-tab');
                if (targetTab === state.activeTab) return;

                elements.tabBtns.forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                state.activeTab = targetTab;
                
                // Refresh messages
                renderMessages(elements.chatBody);
                
                // If Live Support selected and not connected yet, trigger simulation
                if (state.activeTab === 'live' && !state.sarahJoined) {
                    triggerLiveConnection(elements.chatBody);
                }
            });
        });

        // Event: Send Message
        elements.inputForm.addEventListener('submit', (e) => {
            e.preventDefault();
            const text = elements.chatInput.value.trim();
            if (!text) return;

            // Clear Input
            elements.chatInput.value = '';

            // 1. Append User Message
            const activeLog = state.activeTab === 'ai' ? state.aiMessages : state.liveMessages;
            activeLog.push({ sender: 'user', text });
            renderMessages(elements.chatBody);

            // 2. Trigger Reply Simulation
            if (state.activeTab === 'ai') {
                simulateAiResponse(text, elements.chatBody);
            } else {
                simulateLiveSupportResponse(text, elements.chatBody);
            }
        });
    }

    // Render Dashboard UI
    function renderDashboard() {
        const path = window.location.pathname;
        const isDashboardRoute = path.includes('/futurecloud-monitoring') || 
                                 path.includes('/futurecloud-demo') || 
                                 path.endsWith('futurecloud-plugin.html') || 
                                 document.getElementById('futurecloud-dashboard');
                                 
        if (!isDashboardRoute) return;

        // Find or create dashboard root element
        let dbRoot = document.getElementById('futurecloud-dashboard');
        if (!dbRoot) {
            // Overwrite body if it's a dedicated monitoring page path
            dbRoot = document.createElement('div');
            dbRoot.id = 'futurecloud-dashboard';
            document.body.innerHTML = '';
            document.body.appendChild(dbRoot);
            document.body.style.background = '#f8fafc';
            document.body.style.margin = '0';
        }

        // Render Dashboard Structure
        dbRoot.innerHTML = `
            <div class="fc-dashboard-container">
                <!-- Header -->
                <div class="fc-db-header">
                    <div class="fc-db-logo">FutureCloud visitor-monitoring</div>
                    <div class="fc-db-badge">
                        <span class="fc-db-status-pulse"></span>
                        <span>Active Connection</span>
                    </div>
                </div>
                
                <!-- Cards -->
                <div class="fc-db-grid">
                    <div class="fc-db-card">
                        <h4>Total Pengunjung</h4>
                        <div class="fc-db-card-val" id="fc-total-visitors">-</div>
                    </div>
                    <div class="fc-db-card">
                        <h4>Pengunjung Hari Ini</h4>
                        <div class="fc-db-card-val" id="fc-today-visitors">-</div>
                    </div>
                </div>
                
                <!-- Table -->
                <div class="fc-db-table-card">
                    <h3>Log Pengunjung (Visitor Journey)</h3>
                    <div class="fc-db-table-wrapper">
                        <table class="fc-db-table">
                            <thead>
                                <tr>
                                    <th>Waktu</th>
                                    <th>Halaman</th>
                                    <th>Perangkat</th>
                                    <th>Lokasi</th>
                                </tr>
                            </thead>
                            <tbody id="fc-logs-body">
                                <tr>
                                    <td colspan="4" style="text-align: center; color: #94a3b8; padding: 20px;">
                                        Loading visitor logs database...
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    <div class="fc-db-info-footer">
                        <svg style="width:16px;height:16px;" viewBox="0 0 24 24"><path fill="currentColor" d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M12 20C7.6 20 4 16.4 4 12S7.6 4 12 4 20 7.6 20 12 16.4 20 12 20M11 8H13V6H11V8M11 18H13V10H11V18Z"/></svg>
                        <span>Plugin terhubung aktif pada License Key Anda: <strong>${LICENSE_KEY}</strong></span>
                    </div>
                </div>
            </div>
        `;

        // Load Data from API
        fetchDashboardData();
    }

    // Fetch dashboard stats from API, fallback to mock data on error/empty
    function fetchDashboardData() {
        const totalEl = document.getElementById('fc-total-visitors');
        const todayEl = document.getElementById('fc-today-visitors');
        const tbody = document.getElementById('fc-logs-body');

        fetch(`${API_URL}/visitor/stats`, {
            method: 'GET',
            headers: {
                'X-FutureCloud-License': LICENSE_KEY,
                'Accept': 'application/json'
            }
        })
        .then(res => res.json())
        .then(data => {
            if (data && data.visitor_logs && data.visitor_logs.length > 0) {
                populateDashboard(data);
            } else {
                // Fallback to mock data if API succeeded but returned empty
                populateDashboard(mockVisitorData);
            }
        })
        .catch(() => {
            // Fallback to mock data if API is offline or not configured
            populateDashboard(mockVisitorData);
        });
    }

    // Populate HTML with analytics data
    function populateDashboard(data) {
        const totalEl = document.getElementById('fc-total-visitors');
        const todayEl = document.getElementById('fc-today-visitors');
        const tbody = document.getElementById('fc-logs-body');

        // Render Cards with count animation
        animateCount(totalEl, 0, data.total_visitors, 1000);
        animateCount(todayEl, 0, data.today_visitors, 800);

        // Render Table Rows
        tbody.innerHTML = '';
        data.visitor_logs.forEach(log => {
            const tr = document.createElement('tr');
            
            // Waktu
            const waktuTd = document.createElement('td');
            waktuTd.innerHTML = `
                <div>ID Sesi: <span class="fc-db-session">${log.session_id.substring(0, 8)}</span></div>
                <div class="fc-db-date">${log.date}</div>
            `;
            tr.appendChild(waktuTd);

            // Halaman
            const halamanTd = document.createElement('td');
            const pathList = document.createElement('ul');
            pathList.className = 'fc-db-path-list';
            
            log.page_journey.forEach(journey => {
                const li = document.createElement('li');
                li.innerHTML = `
                    <span class="fc-db-path-badge">${journey.path}</span>
                    <span class="fc-db-path-time">(${journey.time})</span>
                `;
                pathList.appendChild(li);
            });
            halamanTd.appendChild(pathList);
            tr.appendChild(halamanTd);

            // Perangkat
            const perangkatTd = document.createElement('td');
            perangkatTd.textContent = `${log.device || 'Desktop'} - ${log.browser || 'Chrome'}`;
            tr.appendChild(perangkatTd);

            // Lokasi
            const lokasiTd = document.createElement('td');
            lokasiTd.innerHTML = `
                <div class="fc-db-location">${log.city || 'Unknown'}, ${log.country || 'ID'}</div>
                <div class="fc-db-ip">IP: ${log.ip_address}</div>
            `;
            tr.appendChild(lokasiTd);

            tbody.appendChild(tr);
        });
    }

    // Counting effect helper
    function animateCount(obj, start, end, duration) {
        let startTimestamp = null;
        const step = (timestamp) => {
            if (!startTimestamp) startTimestamp = timestamp;
            const progress = Math.min((timestamp - startTimestamp) / duration, 1);
            obj.innerHTML = Math.floor(progress * (end - start) + start).toLocaleString();
            if (progress < 1) {
                window.requestAnimationFrame(step);
            }
        };
        window.requestAnimationFrame(step);
    }

    // Scroll chat body helper
    function scrollToBottom(container) {
        setTimeout(() => {
            container.scrollTop = container.scrollHeight;
        }, 50);
    }

    // Render Messages list based on current active tab
    function renderMessages(container) {
        const activeLog = state.activeTab === 'ai' ? state.aiMessages : state.liveMessages;
        container.innerHTML = '';

        activeLog.forEach(msg => {
            const el = document.createElement('div');
            el.className = `fc-msg ${msg.sender}`;
            el.textContent = msg.text;
            container.appendChild(el);
        });

        scrollToBottom(container);
    }

    // Append a single message (without full rerender)
    function appendMessage(container, msg) {
        const activeLog = state.activeTab === 'ai' ? state.aiMessages : state.liveMessages;
        activeLog.push(msg);

        // If tab is still matching, render it directly
        const expectedTab = msg.tab || state.activeTab;
        if (state.activeTab === expectedTab) {
            const el = document.createElement('div');
            el.className = `fc-msg ${msg.sender}`;
            el.textContent = msg.text;
            container.appendChild(el);
            scrollToBottom(container);
        }
    }

    // Render typing indicator
    function showTypingIndicator(container) {
        const indicator = document.createElement('div');
        indicator.id = 'fc-typing';
        indicator.className = 'fc-typing-indicator';
        indicator.innerHTML = `
            <div class="fc-typing-dot"></div>
            <div class="fc-typing-dot"></div>
            <div class="fc-typing-dot"></div>
        `;
        container.appendChild(indicator);
        scrollToBottom(container);
        return indicator;
    }

    function removeTypingIndicator() {
        const ind = document.getElementById('fc-typing');
        if (ind) ind.remove();
    }

    // ==========================================
    // 4. AI & LIVE CHAT SIMULATIONS
    // ==========================================

    function simulateAiResponse(userText, container) {
        showTypingIndicator(container);

        const normalizedText = userText.toLowerCase();
        let reply = '';

        if (normalizedText.includes('harga') || normalizedText.includes('price') || normalizedText.includes('langganan') || normalizedText.includes('bayar')) {
            reply = 'FutureCloud menawarkan paket langganan Fleksibel untuk plugin monitoring & chatbot. Biayanya mulai dari $9/bulan per domain. Anda bisa mengelolanya langsung di Dashboard FutureCloud.';
        } else if (normalizedText.includes('integrasi') || normalizedText.includes('pasang') || normalizedText.includes('cara')) {
            reply = 'Untuk mengintegrasikan plugin ini, Anda cukup menjalankan perintah `futurecloud-monitoring install` via CLI, masukkan License Key, dan pilih framework yang sesuai (Laravel, React, Vue, HTML Biasa).';
        } else if (normalizedText.includes('traffic') || normalizedText.includes('monitoring') || normalizedText.includes('stat')) {
            reply = 'Plugin Traffic Monitoring kami melacak kunjungan secara real-time, tipe perangkat (Mobile/Desktop), browser, sistem operasi, serta durasi sesi kunjungan untuk optimasi website Anda.';
        } else if (normalizedText.includes('halo') || normalizedText.includes('hai') || normalizedText.includes('hello') || normalizedText.includes('p')) {
            reply = 'Halo! Selamat datang di Asisten AI FutureCloud. Ada yang bisa saya bantu terkait monitoring traffic, chatbot AI, atau live chat?';
        } else {
            reply = 'Terima kasih atas pertanyaan Anda! Untuk detail lebih lanjut mengenai fitur FutureCloud, Anda bisa mengunjungi website resmi kami di futurecloud.id atau beralih ke tab "Live Support" untuk berbicara dengan tim agen kami.';
        }

        setTimeout(() => {
            removeTypingIndicator();
            appendMessage(container, { sender: 'bot', text: reply, tab: 'ai' });
        }, 1200);
    }

    function triggerLiveConnection(container) {
        if (state.sarahJoined) return;
        state.sarahJoined = true;

        setTimeout(() => {
            appendMessage(container, { sender: 'system', text: '✔ Terhubung dengan Sarah (Support Agent)', tab: 'live' });
            
            setTimeout(() => {
                showTypingIndicator(container);
                
                setTimeout(() => {
                    removeTypingIndicator();
                    appendMessage(container, { sender: 'bot', text: 'Halo! Saya Sarah dari FutureCloud Support. Ada yang bisa saya bantu terkait integrasi plugin monitoring atau status langganan Anda?', tab: 'live' });
                    state.liveStatus = 'connected';
                }, 1000);
            }, 1000);
        }, 1500);
    }

    let sarahMessageCount = 0;
    function simulateLiveSupportResponse(userText, container) {
        showTypingIndicator(container);

        let reply = '';
        sarahMessageCount++;

        if (sarahMessageCount === 1) {
            reply = 'Tentu! Untuk mengaktifkan monitoring traffic di website Anda, pastikan License Key Anda sudah dimasukkan ke file `.env` di server Anda.';
        } else if (sarahMessageCount === 2) {
            reply = 'Baik, mohon tunggu sebentar saya cek status langganan domain Anda di database FutureCloud...';
            setTimeout(() => {
                showTypingIndicator(container);
                setTimeout(() => {
                    removeTypingIndicator();
                    appendMessage(container, { sender: 'bot', text: 'Semua sistem berjalan normal! Domain Anda terdaftar aktif. Ada hal lain yang bisa saya bantu lagi?', tab: 'live' });
                }, 1500);
            }, 3000);
            return;
        } else {
            reply = 'Siap, terima kasih konfirmasinya! Tim teknis kami akan segera mem-follow up jika ada masalah lebih lanjut.';
        }

        setTimeout(() => {
            removeTypingIndicator();
            appendMessage(container, { sender: 'bot', text: reply, tab: 'live' });
        }, 1500);
    }

    // Initialize UI on load
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
        setupUI();
    } else {
        document.addEventListener('DOMContentLoaded', setupUI);
    }
})();
